
From farmer Tue May 19 08:43:06 1987
Received: by moth; 19 MAY 87 08:43:06 PDT
From: farmer (Define the Universe. Give three examples.)
To: aric, chip, nancy, quantum, sda
Subject: trip notes
Status: RO

To Do List generated by My visit to Q May 11-13:

Bugs:
RESTORE key did not re-enable NMIS. RESTORE KEY PROCESSING REMOVED
Minor problem in rs232.m (moveb #1,dd0d should be move #x10,dd0e).DONE.
In cursor.m, the selfmod code could cause crash/interrupts tears.DONE.
got_HB should clear NAKSNT. DONE.
Make sure indirect jumps can not cross page boundries.
generic_on/off on the host are not replying properly.
ASYNC message for security device seems to cause problems

Design:
Improve disk error detection. DONE
Implement Error Handler (see ERRORS). DONE
Need to limit number of heads on host. (settled on 32, any style)
Add LRC checking, and do it often!
Keep a command history incl noid,class,function (I am not sure this is needed)

ERRORs: (Things we need to trap)
Mem Fault - heap full
Mem Fault - corrupt header
LRC failure
indirect addr error
graphic state of image is out of range
user requested dump.
Disk error warning

From nancy Wed May 20 09:28:23 1987
Received: from kessel by moth; 20 MAY 87 09:28:23 PDT
From: nancy (Nancy Mohler)
To: chip, farmer
Received: by kessel; 20 MAY 87 09:28:19 PDT
Subject: VA visit #2
Status: RO

just talked to Cathy.  told her, as Chip had said yesterday afternoon, that
we're shooting for getting a rev w/diagnostics available to them in the morning
to allow testing before the 3-day weekend.  for sure will have it there before
the weekend.

tentatively planning for you two to go there during the 1st week of June--maybe
the 1st & 2nd to work w/Janet & Mike, & debrief the 3rd?  do you think that's
a reasonable schedule to be able to review info from the diagnostic tools?

things to schedule around:
--their move to the building next door = pack Thursday the 4th, start moving
furniture on Friday, & move the machines between 1:00am Sunday & 6pm Monday.
to be back up at 6:00 Monday night the 8th.
--our all-employee meeting 6/8 at 4:00.
--our Mad Scientist Lecture 6/12.
--access to the stratus for Chip is easiest the week of 6/1.

why don't the two of you stop by about 10 & let me know what you think.  thanks.

From farmer Wed May 20 20:05:33 1987
Received: by moth; 20 MAY 87 20:05:33 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: aric, chip, nancy, sda
Subject: version status
Status: RO

5.2t (test) got tested tonight.
It needs a little more work (hey! alot of new stuffs in dair!:)
Release will be slated for Friday.
,

From farmer Thu May 21 08:35:04 1987
Received: by moth; 21 MAY 87 08:35:04 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer,chip,aric,nancy,sda
Subject: VA Trip II
Status: RO

Just got off the phone with Janet re: 'VA#2'

1) Agreed with me that June 1st is way too soon for ME to
	meet with them.
   (Said that the only reason she gave OK to June 1 trip is because
	Cathy said it was what WE wanted, also date was picked
	by Nancy.(realizing that Chip can only get Stratus access
	thru June 3)

2) Agreed that 'to review diagnostic information' is NOT a good agenda.
   (This info will be reviewed as it is reported, not saved up for later.)

Here is the scoop as Janet and I now understand it:
We agree, that if 
1) a number of UNKNOWN (mystery) problems appear
	(i.e. still getting unexplained meltdowns) and/or
2) Mikey needs to consult with us re:hardware problems,
	that we will get together SOMEWHERE.

This trip would take place AFTER these steps are taken:
1)
 a: Randy looks at ARFS/TAPES/DISKS, and cant figure out what is going on.
	(includes a discussion with Janet)
 b: Aric & Chip look at same problem, and do the same.
 c: There is a phone call (perhaps conference) to discuss the problem(s)
2)
 a: Mike and I can't work it out on the phone.

From nancy Thu May 21 10:29:40 1987
Received: from kessel by moth; 21 MAY 87 10:29:40 PDT
From: nancy (Nancy Mohler)
To: chip
Received: by kessel; 21 MAY 87 10:29:33 PDT
Subject: alpha
Status: RO

Cathy is checking w/Janet for current task summary to review our understanding
of bug fixes required for starting alpha.  The last list I have is 5/7--please
send the most current so we're all looking at the same thing.

The time frame Cathy has in mind is:
week of 5/25  team testing of version 5.2 (w/diagnostics)--back to 6 people
              (3 from there & 3 from here) on Tuesday & Wednesday nights.
week of 6/1  analyze diagnostic results & debugging
week of 6/8  team testing of new rev, possibly w/larger group 
week of 6/15  start alpha if that rev did not fail consistently


Need the daily status report, please!


From nancy Thu May 21 10:31:34 1987
Received: from kessel by moth; 21 MAY 87 10:31:34 PDT
From: nancy (Nancy Mohler)
To: chip
Received: by kessel; 21 MAY 87 10:31:27 PDT
Subject: 5/7 summary report
Status: RO

a couple of notes--#105 is 1B, and #113 is 1A, I think.


From farmer Fri May 22 08:26:52 1987
Received: by moth; 22 MAY 87 08:26:52 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer
Cc: farmer,chip,aric,nancy,sda, quantum
Subject: 5.2
Status: RO

Habitat Version 5.2

This is an internal release copy of Habitat.
With the addition of diagnostics, there have been significant changes
and they require a new round of 'internal' testing (aw,rf,cm,jh,rm,ca)

Changes include:
We lost 256 byts of heap, please adjust on host.
Fixed interrupt tear stuff
HBs always NAKed
Indirect JMP Never on page boundry
RESTORE key processing removed (shift-restore now disabled)
The graphic system has been made more robust (non-crashing)

NOTE!!!: There is a new file on the Imagery Disk:
on_disk_charset.dat lives at Track 0x12 Sector 0x8
(This is so that Imagery disks can have different character sets)

Diagnostics:
When an error occurrs (or the user presses CTRL-C=) a word balloon will
appear with an error/warning message. If the error is Fatal, the user
will be requested to insert a blank formatted disk. This 'DUMP TO DISK'
may be aborted with shift-runstop.

Fatal errors
user_requested_dump	=	0	; no TRAPPED error occurred
memory_full		=	1
memory_fault		=	2
memory_corrupt		=	3	; lrc got corrupted
indirect_address_error	=	4
bad_image_state		=	5
no_room_for_head	=	6
indirect_address_jmp	=	7
indirect_address_rts	=	8
Warnings
simple_disk_error	=	128	; returned by rom
disk_write_error	=	129	; write protect(?)
sector_lrc_error	=	130	; transmission problem	


From nancy Fri May 22 13:37:22 1987
Received: from kessel by moth; 22 MAY 87 13:37:22 PDT
From: nancy (Nancy Mohler)
To: aric, chip, farmer
Cc: sda
Received: by kessel; 22 MAY 87 13:37:17 PDT
Subject: alpha requirements
Status: RO

from conference call Chip & I had w/Cathy & Janet this morning, these are
pre-alpha bugs:
#x39
#113
#115 + note concentrate on testing, since it has turned out to be a little
     trickier than we thought
#165
#167
#173
#176
#184
#tbd flashlight problem
#tbd ESP not sending when point @ teleport booth

we agree that 1 week of testing will be done on the beta lock down version
before starting beta.  max one disk release per week during alpha.

mystery bugs #14, 111, and 124 are being addressed by diagnostics over the next
week or so.

chip will copy quantum on arf list updates frequently.  the 5/7 report is
being updated today.

questions?  thanks.


From farmer Wed May 27 19:18:09 1987
Received: by moth; 27 MAY 87 19:18:09 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: aric, chip, farmer, nancy, sda
Subject: status.
Status: RO


Ok there were a few fatal errors last night:
#1 (memory full)   HOST problem, will work with Janet on this tomarrow
#3 (LRC error) Nancy had pilot error. A patch has been inserted to prevent this.
#4 (missing image) Still working on this.
I inserted lrc checking at the sector level, and discovered that we are
getting errors! Worked to determine cause for 5+hrs.
effect: If a sector lrc error ocurrs (differing freq with different machines),
	we will retry to load that sector.

From farmer Thu May 28 08:39:47 1987
Received: by moth; 28 MAY 87 08:39:47 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer,chip,aric,nancy,sda, quantum
Subject: latest ARFS
Status: RO

ARFs thru 5/28: (version 5.2/5.2a tested)

2B   cr #190 ESP does not work when pointing to oracle (same for BBox)
1A   jcr #191 FE#1 (mem full) avatars being allowed to dghost in full regions
-- D   #192 Nancy have FE#3 (LRC). User error. Dumped to Object Disk.
		(routines patched to prevent recurrence)
-- D   #193 Super trap patterns corrupted. FIXED 5.2b.
       #194 dup #191
2A   r #195 Camera, Lights, Stereo, Sec Dev cause problems async.
1A T j #196 Could not return to PC after FE#1. FIXED
       #197 dup #191
       #198 Long time to initialize (Habitat logo screen)
2A T r #199 Bahia was unable to return to PC. (disk routines improved)
       #200 dup #191
       #201 dup #196
       #202 dup #195
       #203 dup #195
??   r #204 Janet had strange meltdown (awaiting tape)
       #205 dup #196
       #206 dup #191
       #207 dup #193
       #208 dup #193


From farmer Tue Jun  2 08:17:42 1987
Received: by moth; 02 JUN 87 08:17:42 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer,chip,aric,nancy,sda, quantum, wendy
Subject: Habitat 5.3
Status: RO

Habitat version 5.3:

SMALL SCALE TEST TONIGHT.

The good news:
	According to our list 5.3 has all Alpha items complete (some in test)

Exaustive list of changes:
Keyboard echos under interrupt (need through testing:messages/mail)
Problems with generic_broadcast fixed (accounts for #173 Janets meldown)
Stereo, Camera, Flashlights should all be working properly now
The C64 will no longer issue 'unexpected' commands because of throttle delays.
Disk routines now internally check LRC, and retry if bad.
'to:user' works when pointing to teleport if not adj or not active
Corrupted wall/pillar patterns fixed.

Host:
actions_switch fixed.
AskOracle changed to cope with 'to:'
From chip Fri Jun  5 14:54:36 1987
Received: by moth; 05 JUN 87 14:54:36 PDT
From: chip (Chip Morningstar -- "Software Without Moving Parts")
To: aric, chip, farmer, nancy, sda
Subject: The scoop on Telenet
Status: R

As y'all know, we were visited this morning by Carol Brown and Tom Cramer from
Telenet.  They gave Randy and I the detailed scoop on their service and they
left me with a bunch of literature.  The bottom line is that it's pretty
expensive, but there are a lot of options to explore.  The price comes in
several pieces:

I. Accounting charge
	$140/month independent of the number of connections or volume of use.

II. "DAF" (Dedicated Access Facility).
	This is the physical connection to their system.  Included in this is
a dedicated leased line to their San Francisco node, all the wiring into our
plant, modems on both ends of the line, and dedicated access to a port on
their node.  The price varies somewhat with the bandwidth of the connection.
For our purposes the best price/performance tradeoff seems to be at around
9600 baud.  Cost for this is a one-time installation charge of $1200 plus
$1524/month.

III. Traffic charges
	These are billed in units that they call "segments".  A segment is
a chunk of up to 64 bytes of transmitted data.  These cost $1.40 per thousand
(i.e., $1.40 for each 64K bytes of data sent).  There is a 50% discount for
use during non-prime-time hours (ie., after 6pm).  This cost is
distance-independent -- i.e., it doesn't matter how far you are sending the
data.

IV. Dial-in charges
	If we choose to allow dial-in to our system through Telenet, there is
a per-minute charge that varies according to the type of node that you are
connected to.  They classify their nodes 'A', 'B' or 'C' depending on the
level of traffic.  'A' nodes are found in big cities like San Francisco or
Washington, D.C..  'B' nodes are places like Palo Alto or Buffalo.  'C' nodes
are places like San Rafael or Tuscaloosa, Alabama.  Charge varies from around
$5.25/hour for an 'A' node to around $12.50/hour for a 'C' node.  As with
traffic charges, there is a 50% rakeoff for off-hours use.

In addition, we would need to have an X.25 interface on one of our Suns or
Vaxes here.  I'm not sure about the cost, but my guess is that it would be in
the $1000 to $3000 range.  Also, we would still need to obtain some sort of
file transfer protocol software to communicate data with Quanum, since our
computers and theirs have incompatible operating systems.  A call to Sun is
probably in order if we want to pursue this further.

These prices appear to be prohibitive if we were to install such a connection
exclusively for the benefit of Habitat (at least until Habitat becomes a MUCH
bigger deal).  However, there may be additional ways to justify the cost.  For
example, it appears that the company could save about 80% on Telex costs by
hooking to CCI through Telenet rather than by phone.  This is certainly not
enough by itself to recover the cost of the Telenet connection, but it's an
example of the sort of thing we can look for.  The Telenet sales people were
real gung-ho on other uses of their services, such as connecting directly to
OAG to save money on travel arrangements or providing E-mail services to
communicate with productions in remote locations (since Telenet is
international).  I dunno about these, but it probably couldn't hurt to nose
around the company and see what folks could use.  My feeling is that Habitat
really, REALLY wants this, but can't justify it on the basis of current cost.


From farmer Mon Jun  8 08:46:01 1987
Received: by moth; 08 JUN 87 08:46:01 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: aric, chip
Cc: farmer
Subject: New Habitat Commands
Status: RO


Change Containers is an asynchronous command (19) addressed at the region

Parameters: Noid, New Container Noid, New X Position, New Y Position.
	(Note a CHANGE containers call WILL re-render the screen)
	(Note this should NEVER be used to remove a living avatars
		contents from his head/hands/pocket as that avatar
		may be trying to manipulate that object himself.)

Prompt User is an asynchronous command (20) addressed at the region

Parameters: Prompt string (will appear on command line).

	This function will cause the C64 to send the user response
	to the region, using a PROMPT_REPLY message (7). This should
	do exacly what we want in regaurds to sending arbitrary text
	commands to the host. The commands will be sent by whatever (magic?)
	class, and the results will be interpreted in class_region. I
	suggest that EACH Prompt User call use completely unique text to keep
	intepretation as simple as possible (the text should conatin a
	std delimiter ':' would be nice).


From farmer Wed Jun 10 10:16:15 1987
Received: by moth; 10 JUN 87 10:16:15 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer,chip,aric,nancy,sda, quantum
Subject: Habitat 5.4
Status: RO

Habitat version 5.4 6-10-87:


The good news:
	According to our list,5.4 has all Beta C64 items complete or in test

Exaustive list of changes:
C64 can now cope with the 'death-while-awaiting-reply' condition.
Two new REGION kernal commands have been added (in test):
	CHANGE_CONTAINERS 	19, an arbitrary change of containership
	PROMPT_USER		20, command promts user on text line

Host:
No Changes. (but some of the grabthese files were not grabbed last release)

From farmer Thu Jun 11 09:22:08 1987
Received: by moth; 11 JUN 87 09:22:08 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer,chip,aric,nancy,sda, quantum
Subject: Habitat Hardware
Status: R

Here is the latest status (as of Tuesday) re: C64 hardware problems.

I (thru Janet) have been in contact with Jim Gracely at commedore about
the problems Habitat is having on some C64s. He listed 3 problems he
'knew' about (i.e. people had reported.). Jim was/is affiliated with
a C64 magazine, and is NOT a C64 tech proper.

	1) There were 2 versions of the VIC-II chip, there is a inconsistency
		on how the MSB of the raster Interrupt is handled.
		(Habitat accounts for this. No Problem for us.)

	2) It is possible to overload the on-chip interrupt stack. This
		has actually happend to other applications. Symtom: The
		screen interrupts would die (meltdown).
		(I told jim what interrupt sources we have, he is
		investigating with C64 techs whether SOME machines might
		have a problem with all our interrupt sources.)

	3) 'Ram under BASIC might could get corrupted.' To his knowledge,
		this has only happened to 'Jumpman'. IF this can happen
		AND we can't program around it, it would be a problem.
		(We need that 8k Under Basic! read:a 64k machine with only
		56k working is DEFECTIVE.)
		(I have Jumpman's designer's name and phone#. Will
		call him ASAP.)


From farmer Mon Jun 15 14:34:32 1987
Received: by moth; 15 JUN 87 14:34:32 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer,chip,aric,nancy,sda
Subject: 5.4 tes
Status: RO

There will be a playtest of version 5.5 tomarrow.
What will make version 5.5 different?
1) People will be able to dump to disk EVEN if comminucations is hung.
		(to help debug this problem that showed with 5.4)
2) In our ommunications with C64, an ex-techie thinks he knows why
	Habitat ,ay be creashing..it has to to with mixed modes & sprites.
	Anyway, I will install a patch per his instructions.
3) A minor problem with the head hack (causing FE#4s) has been fixed
4) Some new images will be availible.

Nothing, just getting the data we need to decide if we are ready for Alpha.

From nancy Mon Jun 15 20:16:48 1987
Received: from kessel by moth; 15 JUN 87 20:16:48 PDT
From: nancy (Nancy Mohler)
To: aric, chip, farmer
Cc: nancy, sda
Received: by kessel; 15 JUN 87 20:16:45 PDT
Subject: HabiTeam 6/12
Status: RO

6/12 Habitat team meeting notes--

5.4 was playtested Thursday night, still evaluating results.
--animation glitch tape coming (Janet saw flashing s, have to do w/tokens?)
--communications problem tape coming (Rob survived when the other 5 went
into a communications loop)
--lights being fixed (Jo's flishlight in sewer, probably
host-based--checkpoint region for light level changes?)
--2 minor arf's from Chip
  1) improve paper help
  2) don't remember, bringing in notes from home
--sound glitch noted but likely to be left as is (lose one voice of the
three during one in 256 region transitions)

Only known remaining pre-alpha bug is the communications problem.  Will
determine Monday from the tape how serious it is.


Organization of playtests to be clarified (Cathy & Nancy noted apparent lack
of leadership).  Randy & Janet will pre-plan.


Plan for next week:
Chip--Plex (pretty much done, adding features as Randy uses it) plus more
Ghu.  Integrate Plex, Riddle & host database.  Work with Gary on new artwork.

Randy--evaluate tapes from 5.4 playtest & debug communications problem.
Continue generating Quantumgrad.  Continue seeking info on hardware
compatibility.

Aric--evaluate tape & debug animation glitch.  Mostly on Blackhawk.


Remaining pre-release world generation:
(Chip will distribute updated old-format task list, reviewing those during
beta & pre-release tasks.)
--need 7 cities to handle 20,000 accounts.  Pop. done.  Quantumgrad expected
to take 2 more weeks (6/26).  Given tools developed during generation of
Quantumgrad, then expect need about 2 days per city or 2 more weeks (7/10).
--also expect to complete the stock market, Capture-The-Flag, and arcades.
--"below the line" world generation that will likely be completed prior to
release is a magic castle and more board games.


Next steps:
1. Randy evaluate communications problem--may require another "technical
test".
2. Given comm bug fix, Randy & Janet will organize 16 person pre-alpha test.


Next team meeting will be 9:30 Friday morning, 6/19.

From nancy Fri Jun 19 11:50:53 1987
Received: from kessel by moth; 19 JUN 87 11:50:53 PDT
From: nancy (Nancy Mohler)
To: aric, chip, farmer
Cc: nancy, sda
Received: by kessel; 19 JUN 87 11:50:48 PDT
Subject: HabiTeam meeting notes
Status: RO

6/19 Habitat team meeting notes--
(Chip & Randy)


*Hardware problem exploration top priority the past week for Janet & us.
Kimsey meeting with Commodore next week, and QL position on the issue being
put together.  
--The problem may be isolated to VIC chip, rev. 1--that's what Janet's seen
on a machine there, and Randy is checking the one that he's been able to
reproduce problems on, and Chip will bring in and check the SX64 portable.  
--Randy & Janet will talk today, and set up conference call to include Mike
Ficco & the ex-Commodore tech guy (he thinks it has to do with mixed
graphics modes & sprites).  
--We need to: 1) demonstrate that there is a hardware problem and try to
isolate it, 2) understand exactly what's happening to see if software work
around is possible, 3) determine, via beta test, if it would be worth major
software change.

*Communications problem still needs testing.  May get data on it from 5.5
playtest tape where Bahia hung (he could not dump).

*Avatar in 2 regions at once problem, Janet looking into a change she had
made on the host that may have introduced it.  Randy's diagnostics made it
understandable.

Accomplishments of past week:
Chip--Plex needs only to have output form decided on for it to be finished.
Continued work on integrating the tools (Ghu now outputs in Riddle form).
Made some cosmetic changes to guns, etc., and improved paper help.

Randy--explored hardware problem & debugged.  Quantumgrad waiting for tools
and region design.  Found 1K heap space w/Aric.

Aric--helped Randy w/hardware diagnostics.  Integrated some new art?

Plan for next week:
Chip--Continue work on database tools--expects 2 more days needed to finish
integration, and needs to decide output form for Plex.  Test the cosmetic
changes (guns) and paper help.

Randy--Quantumgrad region design.  Release 5.6.

Aric--tbd


Next steps:
1. Playtest 5.6 Monday night, then likely ramp up to 16 testers on Tuesday
night, to learn about the communications problem & hopefully isolate
hardware.


Next team meeting will be 1:00 Friday afternoon, 6/26 (changed from usual
9:30 due to 10:00 Intel meeting).
From chip Thu Jun 25 17:03:25 1987
Received: by moth; 25 JUN 87 17:03:25 PDT
From: chip (Chip Morningstar -- "Software Without Moving Parts")
To: aric, farmer
Cc: chip
Subject: Griddle
Status: R

Griddle is now working.  It can read "griddle", "raw" or contents vector files
as input and produce any or all of these as output.  It reads 'define'
statements in exactly the same format as that read by Ghu, so class
definitions at least have a common representation across systems.

One problem did become apparent, however, as I got the code to read contents
vectors working: translations between "griddle" format and "raw" format can be
made in either direction with no loss of information.  The important
difference between the two forms is in the use to which they are put.
Conversion into contents vector form also causes few problems, though we did
discover the funny with capacity count today.  Conversion FROM contents vector
form, however, presents us with a significant difficulty: information is
simply LOST, since the C64 does not keep all the state information that the
host keeps.  Furthermore, once the divergence between the host-form and the
C64-form has happened, there is no way, given the present system, to get back
the lost information and merge it with any changes that might have been made
using Reno (we can and do set the lost field values to their defaults, but
this is often incorrect).

What we need is something analagous to the the Sun frontend for FACE -- a
program that would keep track of what you are editing and hold the host-only
information until you are done.  This program would represent everything on
the Sun end in griddle or raw format.  The contents vector format would become
exclusively a data transmission format.  Whaddya think?

Meanwhile, I am now modifying Ghu to be able to output "raw" files and to both
read and write "raw" and "griddle" files.

Also, the Ghu 'riddle' command will turn into the 'griddle' command, of course
:-)


From nancy Tue Jun 30 14:02:28 1987
Received: from kessel by moth; 30 JUN 87 14:02:28 PDT
From: nancy (Nancy Mohler)
To: sda
Cc: aric, chip, farmer
Received: by kessel; 30 JUN 87 14:02:24 PDT
Subject: Habitat update
Status: RO

as you requested as the project leader meeting this morning.

Randy just said that playtesting is ramping up, starting tomorrow evening. 
He'll mail info.

Jack Daggett said that a guy they talked to at Epyx thought that split screen
was our problem, and that with all of their development efforts they'd
found no solution (except to bit-map screen).  Jack has not looked at Maniac,
and will confirm with Janet that, even though it uses split screen, it doesn't
crash on her bad machines.  Quantum continues to talk to Commodore to try to
find solution to the problem of VIC chip going off & trashing its own
memory.  Their (Quantum's) feeling, per Jack, is that it's in millions of
machines.



From nancy Tue Jun 30 14:07:15 1987
Received: from kessel by moth; 30 JUN 87 14:07:15 PDT
From: nancy (Nancy Mohler)
To: chip
Received: by kessel; 30 JUN 87 14:07:12 PDT
Subject: the H word
Status: RO

as in Hardware.  Are you expecting Quantum to find out something more specific
than, "VIC chip going off & trashing its own memory?"  Is there anything els
--else that we should be hearing from them to help find work around?  (other
than MORE testing)
thanks.


From nancy Tue Jun 30 15:16:27 1987
Received: from kessel by moth; 30 JUN 87 15:16:27 PDT
From: nancy (Nancy Mohler)
To: chip
Received: by kessel; 30 JUN 87 15:16:22 PDT
Subject: Re:  the H word
Status: RO

for grins, let's assume that there are so many "bad" Commodores out there that
we can't ship Habitat as currently designed.  If there's not technical
solution to work around the bad vic chips, is there a design solution?

thanks.


From nancy Tue Jun 30 15:50:02 1987
Received: from kessel by moth; 30 JUN 87 15:50:02 PDT
From: nancy (Nancy Mohler)
To: chip
Received: by kessel; 30 JUN 87 15:49:56 PDT
Subject: Re:  the H word
Status: RO

hum.  your previous message said there didn't seem to be a technical work 
around, and this message makes the design work around seem to be ruled out as
well.

In order to understand the problem well enough, what do we need (other than to
know how many bad Commodores there are)?  do we know?  or is the plan to 
patiently hang in there while Jack, et. al., looks for a technical work around
to the vic chip, unlikely as it may be?  what am I missing?

thanks.


From nancy Tue Jun 30 20:59:03 1987
Received: from kessel by moth; 30 JUN 87 20:59:03 PDT
From: nancy (Nancy Mohler)
To: chip
Received: by kessel; 30 JUN 87 20:58:59 PDT
Subject: friendly reminder
Status: RO

to see if Rob Fulop can give us any insight into the hardware issue.  if you
think it makes sense for the two of us to discuss on a conference call wi/him,
let me know.  thanks.


From sda Wed Jul  1 08:45:45 1987
Received: from kessel by moth; 01 JUL 87 08:45:45 PDT
From: sda (Steve Arnold - Games Division)
To: chip
Cc: nancy
Received: by kessel; 01 JUL 87 08:45:42 PDT
Subject: more info on gs and amiga
Status: RO


what would we need to do to get more detailed information on the
difficulties and risks of converting habitat to the GS and Amiga?
is this something you and randy can explore with others in the group?
or do we need to get outside information?  i'd like to get enough
information to be able to estimate manmonths of work to get a version
working on each of the machines.  please rsvp.


From nancy Wed Jul  1 10:13:39 1987
Received: from kessel by moth; 01 JUL 87 10:13:39 PDT
From: nancy (Nancy Mohler)
To: chip
Received: by kessel; 01 JUL 87 10:13:36 PDT
Subject: Re:  friendly reminder
Status: RO

try (415)323-1916 for Fulop.  I'm not sure if it's current--let me know please
if it doesn't work.


From nancy Wed Jul  1 13:32:34 1987
Received: from kessel by moth; 01 JUL 87 13:32:34 PDT
From: nancy (Nancy Mohler)
To: sda
Cc: chip, nancy, ron
Received: by kessel; 01 JUL 87 13:32:28 PDT
Subject: Maniac & QL
Status: RO

Ron, Chip & I talked to Janet (Jack tied up in a meeting).  Maniac is not an
example of the suspect split screen w/sprites problem.  There's no bit map in
it at all--entire screen is character set.

So...Janet's still looking for info on the split screen w/sprites crossing
interrupt boundaries--still suspect that Habitat's problem is related to
switching the modes and sprites crossing character boundaries.  Since we can't
think of examples of any programs doing that, Janet plans to program test cases
tomorrow (using Ron's Programmer's Basic toolkit that we're fedXing to her).

Chip & Ron, please add to this if there's more info that you think would help.
Thanks.


From farmer Thu Jul  2 08:42:59 1987
Received: by moth; 02 JUL 87 08:42:59 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer,chip,aric,nancy,sda
Subject: Last nights playtest
Status: RO


Here's the results:

1) The host was confused about Vendo, Paper, Atms, etc...
	This was Janets fault and has been fixed
2) dv Had a get/put wars hang (host)
3) auto-teleport to a region you are already in can kill any async avatars
		(host)
4) Janet had problems picking something up from the left side.
5) 1 person had problems returning to People connection.

The effects:

Another playtest tonight! Janet is in full agreement that we should
continue larger-scale testing. Alpha next week look REAL good. (the
remaining C64 problems, we agree, will NOT hold up alpha. Just the
BIG host ones.)

Who's gonna play tonight? ;)


From farmer Thu Jul  2 08:46:00 1987
Received: by moth; 02 JUL 87 08:46:00 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer,chip,aric,nancy,sda
Subject: 2 week summary
Status: RO

OK the list of new problems discovered in the last 2 weeks:

*=host			(total 13)
+=C64 Behaviour		(total 1)
-=C64 code		(total 1+3?)	<---- note the host/c64 ratio!

*+	Guns don't work on avatars heads
*	Guns don't work on avatars if they ghost/leave region
*	If a region transition fails, the light level is wrong
				and the avatar 'on-hold' bit wrong
*	Regionproc crash (null pointer)
*	Avatar in two regions at the same time
*?-?	Communications hang. Seems to be related to boxes/bags
*	Vendos/Atms/Token merge/PaperPad all broken (Fixed)
*	dv hung when he PUT down a head when someone else had grabbed it.
*	Auto-teleport (escape device) causes crash in asynch case.
*	two people open a box at the same time (Fixed)
*	book/plaque changed so that it gets last-page-number from text db.

-?	Bahia got an 'impossible' heap overrun. A diagnositic has been
		inserted (Fatal Error 9)
*	Gr state of heads in containers is not properly set.
		(check head-get code on host)

*?-?	Grab from left hand side sometimes doesn't work.
-	Return to people connection failed?


From farmer Fri Jul  3 07:44:30 1987
Received: by moth; 03 JUL 87 07:44:30 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: gdiv, quantum
Subject: Thusrday Habitat Test
Status: RO


The results of the Thursday Habitat Test: (Drum roll please!)

NO PROBLEMS.

About a dozen people were on in several small groups.


What this means (agreed with Janet at Quantum):
We (and Janet) will fix the remaining problems reported in the last
4 playtests (95% on host, and minor). 

Then, on Tuesday will be a Habitat Pizza Playtest Orgy.
If Habitat passes that test, THAT version (5.7) will be the
ALPHA test version of HABITAT! (Yea!)

(Alpha test consists of 50 avatars, most of whom have never been in Habitat
Before)


From farmer Fri Jul  3 07:59:08 1987
Received: by moth; 03 JUL 87 07:59:08 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: aric, chip, ron
Cc: nancy, sda
Subject: Good (?) News
Status: RO


Janet recived Graphics Basic, and had no problems creating a 
textmode/bitmap screen and running sprites all over the screen.
This WORKED on the 'bad' machines. On Monday, she will work with Doug
to add NMI timers to the program, and see if that has any affect (I bet it
does!)

I told her about the vblank-less version, and will release it as version 5.7
fpr upload Monday.

From chip Tue Jul  7 20:22:43 1987
Received: by moth; 07 JUL 87 20:22:43 PDT
From: chip (Chip Morningstar -- "Software Without Moving Parts")
To: nancy, sda
Cc: aric, chip, farmer
Subject: Playtest report
Status: R

Quick summary: Major though not ultimate success.

In more detail:

We had a large enough group of people on that I couldn't keep track of how
many there were.  My guess is that it was somewhere in the neighborhood of 10
or 12.  The major result is that we convinced ourselves of what we always
suspected: playing habitat with three or four people has a funativity
coefficient of 3.7, while playing with a large number of people has a
funativity coefficient of 11.2.  People played for a good solid couple of
hours and were still going at it when I signed off.

There were a few problems, though their significance is unclear.  Rasputin had
a fatal error #3.  Noah had a fatal error #4.  Janet saw some messed up color
RAM.  We got dump disks on all of these.

It looks like we are in pretty good shape, though we don't have an unqualified
green light for Alpha just yet.  Janet indicated that she would like to set up
a systematic test of all the object classes.  The logistics of this will have
to be worked out, but we can probably do it during the daytime with three
people, rather than requiring a formal evening playtest.  I will work on a
plan for this.

Randy will no doubt be on the phone with Janet tomorrow morning with the
verbose feedback from Virginia.


From nancy Wed Jul 15 09:37:14 1987
Received: from kessel by moth; 15 JUL 87 09:37:14 PDT
From: nancy (Nancy Mohler)
To: aric, chip, farmer, sda
Received: by kessel; 15 JUL 87 09:37:10 PDT
Subject: Cathy
Status: RO

called w/congrats!  Janet ran the new Habitat rev. for 20 minutes on the
bad machine (only 20 because the system was brought down).  she said Randy &
Janet were planning playtest of it tonight, & Cathy will call Friday about
alpha test organization.  and, we'll schedule meeting w/her here next week when
Cathy is back out this way.

whew!  good work.


From farmer Wed Jul 15 10:30:54 1987
Received: by moth; 15 JUL 87 10:30:54 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer,chip,aric,nancy,sda
Status: RO

>From MAILER-DAEMON Tue Jul 14 18:20:33 1987
Received: from shem by moth; 14 JUL 87 18:20:33 PDT
>From: MAILER-DAEMON 
Status: R

7 1987
To: farmer
Subject: error in mail

send-mail: user gang unknown
Mail on shem not delivered to:
gang

--------------returned mail-----------
Received: by shem; 14 JUL 87 18:20:34 PDT
>From: farmer 
To: gang, quantum
Subject: Version 5.8

Habitat 5.8 has been released and is ready for upload (Qlink mail sent)

Two differences:
1) So that Habitat will run on machines with bad VIC chips, the text line
    has been moved to the TOP of the screen
2) We lose a page of memory (Actualy we GAIN about 5-6 pages, I have just
 not have had time to do the memory shuffle)

We should have a small scale test (with no changes to the host).
There will be a 5.9, with increased heap & whatever the test reveals
are bugs with the new text-line positioning

Yeah!



From farmer Wed Jul 15 14:38:01 1987
Received: by moth; 15 JUL 87 14:38:01 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer,chip,aric,nancy,sda
Subject: Heap
Status: RO


Old		New		Gain
14848		16704		1856 bytes!

;)

From farmer Wed Jul 15 14:44:41 1987
Received: by moth; 15 JUL 87 14:44:41 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: aric, chip
Subject: Rev II
Status: RO

Habitat Memory Map As Of July 14, 1987

0000-00ff	Zero Page (shared with behaviors)
0100-01ff	Stack
0200-0816	Variables (shared with behaviors)
0816-4000	Program Code
4000-43ff	Sprite Images	<-start VIC Bank
4400-47ff	Text/Color Map & Sprite Pointers
4800-49ff	Variables
4a00-4b3f	Bounce Buffer
4b40-5f3f	Bitmap Page 1
5f40-5fff	Program Code
6000-63ff	Character Set (128 characters)
6400-67ff	Tables
6800-69ff	Variables
6a00-6b3f	Bounce Buffer			6a00-77ff  Init/Loader
6b40-7f3f	Bitmap Page 2			7800-
7f40-7fff	Variables	<-end VIC Bank	    -7fff  Customizer
8000-809e	Jump Vectors  (shared with behaviors)
809f-		Program Code
		Variables
aa00-eb3f	Heap				e340-eb3f  Relocated Customize
eb40-ff3f	Background Buffer
ff40-fff9	Program Code
fffa-ffff	Interrupt Vectors

From farmer Thu Jul 16 18:34:44 1987
Received: by moth; 16 JUL 87 18:34:44 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer,chip,aric,nancy,sda, quantum
Status: RO


Released:
Habitat 5.9 includes:
1) Cursor clipping adjustment
2) Cleanup of 'exit-paper'
3) A fix to the animation engine
4) Bigger Heap (New size on host 16500 bytes!)

Lets Do It!

From nancy Fri Jul 17 14:33:20 1987
Received: from kessel by moth; 17 JUL 87 14:33:20 PDT
From: nancy (Nancy Mohler)
To: aric, chip, farmer
Received: by kessel; 17 JUL 87 14:33:16 PDT
Subject: Cathy
Status: RO

will be here Friday morning, about 9:30, to discuss test plan & release
requirements.

she & Rob have talked about putting together logistics for beta test.  He plans
to have message boards up by Friday.  Their new QC person will be getting
involved starting Monday.

for release requirements, Rob's putting together a list of things like
publications needed & tools to support the world.  we'll review that on Friday.

told Cathy that Chip was posting today an update to the bug & task list status,
as we discussed this morning (group bugs by ones that may have been fixed by
the hardware fix so need to be replicated, ones that are on the host for us to
fix, on the host for Chip & Janet to follow up on, etc.).  Cathy confirmed that
Janet plans to keep the packet trace on the host.

the time frame they have in mind for testing:
week of 7/20--heavy test w/regulars + a few (16-20 people total, with about 12
  on each night, including 4 from here--we'll both recruit as many people as we
  can)
week of 7/27--slow down for vacation time.  Randy's scheduled to be out that 
  week, & Cathy anticipates many of their testers to take time off (post Apple
  push slump, to recover before Apple & Habitat beta test).
week of 8/3--"limited alpha", w/20-30 in-house Quantum people testing
  for a solid week
week of 8/10--add "friendlies" for another week
week of 8/17--official beta start

all for discussion on Friday.

Chip, please remember to send the updated list and to mail gdiv about 
Wednesday afternoon Habitat presentation.


From farmer Tue Jul 21 07:30:18 1987
Received: by moth; 21 JUL 87 07:30:18 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer,chip,aric,nancy,sda
Subject: Playtest
Status: RO


Last night we had a 14+ user playtest...Results:

Only 2 'cosmetic' problems reported:
The text area sometimes 'flashes'  <--- non-fatal, possibly unfixable
With the new pointer system, it can be VERY hard to point at animating
juggling balls.

Janet agreed that niether of these are high priority, and even if we
CAN'T fix them, it is no big deal.

The test was a MAJOR success. Alpha Here We Come!

From crock Tue Jul 21 07:52:02 1987
Received: from kessel by moth; 21 JUL 87 07:52:02 PDT
From: crock (Douglas Crockford - The happiest man in the vast wasteland)
To: aric, chip, farmer
Cc: nancy, sda
Received: by kessel; 21 JUL 87 07:51:37 PDT
Subject: Habitat
Status: RO

Last night I took my first step into a smaller world.

These are some of my reactions to that first experience:

JOYSTICK.  There are four iconic commands which are overloaded onto the
joystick.  Three of the four have a strong directional component:  pick UP,
put DOWN, go RIGHT there.  Currently, the joystick assignments are
pick LEFT, put RIGHT, and go UP there.  It's not a big deal, you quickly learn
how to generate the correct command, but I think you could have a really nice
mnemonic aid built right in.

MAPS.  In my two hours in Habitat, I was unable to get oriented.  I bought
a map and found it to be incomprehensible.  I think the big WEST convention
is at best confusing.  Even worse, on the map I bought, SOUTH is at the top.
Map reading skills are generally poor in our society.  If you are deliberately
violating one of the few well understood cartographic conventions, I hope you
have a really good reason.

GUIDES.  The thing I did that I found the most rewarding was following people
around, like following the blue tenticle into the hottub, or following a 
couple of guys through the sewer.  The thing Habitat most needs is people.  I
think that if you get it finished, then they'll be there.

MUSIC.  It is really important to have scene transition music.  You need much
more variety.  The little 8 note ditty you have now gets tiresome real fast.
If we could get rights to the Final Jeopardy tune, it would be best.

PIECES OF PAPER.  I hate the convention of dropping paper on the ground in
order to get rid of it.  I find that morally and environmentally irresponsible.
I would rather that I could make my mail disappear Like Magic than to
symbolically litter.

TYPING.  On a number of occasions, when typing my second line of dialog, the
first few characters of the second line got lost.

BIG FINISH.  I think you guys are onto something really neat.  I think it is
worth taking to completion.  Wrap it up.  Ship it.

From farmer Tue Jul 21 08:09:36 1987
Received: by moth; 21 JUL 87 08:09:36 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: aric, chip
Subject: Sex Changer
Status: RO


It seems the sex changer is broken....
Writes memory in BAD ways  (LRC error, In one case 'warped' an
avatar to another place on the screen)

From farmer Tue Jul 21 08:45:50 1987
Received: by moth; 21 JUL 87 08:45:50 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: aric, chip
Subject: Iamges
Status: RO


Is someone keeping a list of images we want?
I have another one:
Domestic Pottery (for Plants)
	1 large pot
	1 small pot
	1 'window' planter

From nancy Tue Jul 21 09:13:59 1987
Received: from kessel by moth; 21 JUL 87 09:13:59 PDT
From: nancy (Nancy Mohler)
To: sda
Cc: aric, chip, farmer
Received: by kessel; 21 JUL 87 09:13:53 PDT
Subject: Re:  test plan
Status: RO

that "test plan" was the time frame that Quantum has in mind, per Cathy.
Chip, Randy, Aric & I will be discussing it this week, and meet w/Cathy this
Friday to agree upon a complete test plan--including release requirements &
target date.


From aric Tue Jul 21 11:07:07 1987
Received: from shem by moth; 21 JUL 87 11:07:07 PDT
From: aric (Aric Wilmunder)(esruoc fo ,esrouc fo ,esroh a si esroh a)
To: chip, farmer
Received: by shem; 21 JUL 87 11:07:05 PDT
Subject: a couple o' tings
Status: RO

	On exhaustive testing.... it would be nice to add sound effects to
sync and async die roll

	Two things on the host.... first, avatars really should deghost on 
login.  If they don't, we should have a good explanation in the manual for
novice users.  Second, having the host send a text message to the user if
the region he is trying to enter is too full would be nice and easy to do.

	I am going to look at the new pointer system with the special cases
of juggling balls constantly moving and the amulet with the clear area in
the middle.


From aric Tue Jul 21 11:21:19 1987
Received: from shem by moth; 21 JUL 87 11:21:19 PDT
From: aric (Aric Wilmunder)(esruoc fo ,esrouc fo ,esroh a si esroh a)
To: chip, farmer
Received: by shem; 21 JUL 87 11:21:17 PDT
Status: RO

>From fanny Tue Jul 21 09:35:18 1987
Received: from hoth by shem; 21 JUL 87 09:35:18 PDT
>From: fanny 
To: aric
Received: by hoth; 21 JUL 87 09:35:12 PDT
Subject: playtest
Status: RO


well it was interesting. I found it very difficult to type, move, read and
make sure no one gave me or took anything away from me. I had a problem
with the money I took out of your account though, I would get some, put
it in my pocket and then when I went to spend some it wouldn't be there.
One time I think someone took it from me and another time it just dissapeared.
If it did because I didn't have room in my pocket I think the game/oracle should
tell you that. Anyways I was glad to help out. How was your game?

From farmer Tue Jul 21 13:47:46 1987
Received: by moth; 21 JUL 87 13:47:46 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: dv, farmer,chip,aric,nancy,sda
Cc: charlie
Subject: Habitat
Status: RO

For Your Convenience:
Habitat will be down tonight for Bandwidth Reduction tests.
Only persons with Bandwidth Reduction ON will be able to enter the system.
(This is a limited scope test. Things will return to normal tomarrow)

See you on the other side (tomarrow ;) )
Randy
.
From farmer Thu Jul 23 15:03:46 1987
Received: by moth; 23 JUL 87 15:03:46 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: aric, chip
Subject: Prioritized:
Status: R

The 1st Habitat All Class Test Results:

S = Stratus  64= Commedore
C = Causes crash (hang)  I = Important  + = Not so important   - = CBB


SC	Boomerang DO Hangs the C64
SC	Matchbook crashes the host (DO)
SI	Pawn machine dispenses a BAD token, value 1, restriction bit set.
SI	Knick_knack (and others) need style based help.
SI	When PUTing paper to dropbox, restriction bit gets set (!?)
SI	Drugs: effects? Help gives effect, remaining #. Bottle not getting
						deleted on host.
S+	ATM needs ASYNC chore for Deposit/Withdrawal
S+	game_piece HELP need 'kingme' instructions
S+	bag/box help needs to give KEY number
S+	Door help CBB
S+	Elevator 'Bad address' msg not appropriate.
S+	Grenade doesn't work.
S+	TALK to hand of god is illegal (!?)
S-	If you put a blank sheet of paper on a countertop, you can take items
S-	Cant we fold the frisbee into another class?
S-	Hole help should match ground help
S-	Fortune Machine async chore CBB

S64C	Ticket DO hangs the 64.
64C	async Sex_change hangs 64.
64I	Keys DON'T WORK.
64+	Bottle DO ground beeps.
64-	Add sfx to Die object
64-	The ring image looks like a pill.
64-	Club Image is all black, should it be all blue?

We should delete these classes:
instant object pill
hat
security device
jukebox
river
roof
stereo (tape play image become either knick-knack or two-state-object)
tape

From farmer Fri Jul 24 14:34:42 1987
Received: by moth; 24 JUL 87 14:34:42 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer,chip,aric,nancy,sda
Subject: Habistatus
Status: R


OK, there is a new version of the Habitat Program, 6.0
but, since Janet is also going on vacation, it will not be released until
8-3.
In the program itself, there was only one change: shft-home will clear
the text line.
(Oh yeah, aric also fixed a problem with pointing to juggling balls)

The following items have been fixed as a result of the All Class Test:
Club image is now blue
DIE do makes noise (sync AND async)
Keys work
Async sex changer fixed

The folloing have been coded, but not tested:
Pawn_machine dispensing bad tokens.
Drug bottle doesn't disappear.
ATM needs async chores
Foretune Machine (same)
Ticket DO doesn't work.

The following classes have been deleted fromthe host & test system
& the C64 databases:
hat, security_device, jukebox, river, roof, stereo, tape

The following things are NOT problems with the class, and should be
removed from the task list:
fold frisbee into another class
Bottle DO ground beeps
blank sheet of paper re:countertop
TALK to hand of god is ILLEGAL.



Need to be done (while I'm Gone):
Test system needs to move over to BANDWIDTH reduction.
Chip needs to test/fix the remaining items on the Class Test Results list.
The Alpha Test-Plan should be in place.

6.0 is gonna be it, so lets be sure ;)!

In case you are wondering, I will be available tonight and tomarrow
if you MUST call me for an emergency (707-585-9803)
I will be incommunicado Sunday thru Friday. You can reach me
NEXT Saturday (all day) or Sunday (1pm-5pm or 8pm-).

Hold down the fort folks!
(I am REALLY nervous about leaving the baby all this time, you take
REAL GOOD Care of her, OK Guys?)

I will read my mail when I arrive Saturday.

From chip Mon Aug  3 15:46:30 1987
Received: by moth; 03 AUG 87 15:46:30 PDT
From: chip (Chip Morningstar -- "Software Without Moving Parts")
To: nancy, sda
Cc: aric, chip, farmer
Subject: Status summary for the week
Status: R

We are, more or less, in Alpha test.  We are proceding according to the plan
proposed by Cathy Anderson in her memo of July 21.  The major implications of
this right now are that we will have more people on in the evenings and we
won't be releasing new revs of the C64 software as frequently.

Randy did the exhaustive all-class test during the week before his vacation.
He and I have fixed almost all the things that turned up as a result of that
(most of them were on the host).  The latest rev of the C64 code is version
6.0.  Janet is uploading it tonight and will be distributing it to everyone on
the East coast tomorrow (she would be doing this today but technical
difficulties on their end messed her up).  The name of the game from here on
out is testing, bug fixing and world generation, rather than new features!

I spent most of the past week working on tools (after taking care of the stuff
from the all-class test).  Ghu is now a very flexible and powerful tool, and
Randy and I have both been using it extensively.  We can now do with at 3 line
command what used to require a PL/1 program and half a day's effort.  There
are still a few more features we want to have in Ghu (notably: commands for
manipulating the book/text database) but it is now usable in a major way.

Randy and I will likely start in on finishing Quantumgrad this week.  However,
among other things, we decided in our meeting here with Cathy a week ago
Friday that we will put an apartment building into Populopolis first.  This
will enable us to 1) work through the process of apartment generation (and
make sure all the tools are working the way we want), 2) test the apartment
building concept itself for players and 3) provide a larger supportable
population base for Beta, thus killing three birds with one stone.


From farmer Mon Aug  3 10:34:29 1987
Received: by moth; 03 AUG 87 10:34:29 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer,chip,aric,nancy,sda, quantum
Cc: wendy
Subject: Release 6.0
Status: RO

Habitat version 6.0 8-3-87:

Alpha Test, Phase II version.
Starting this release, there will be a C64 program release NOT MORE THAN
once per week.

C64 main-program changes:
SHIFT-HOME (clr) now clears the/one text line.
The pointer system can now cope with Juggling balls, bottles, and the like.

C64/Host Changes (classes):
The following classes have bee deleted from the Test, Production and C64
Databases:
11 boomerang
39 hat
40 instant object
63 security device
70 stereo
71 tape
145 jukebox
148 river
149 roof
Note: The C64 will CRASH if the host provides one of these in a contents
vector.

There were several items turned up during the all class test, these are in
various states of test, 90% of them are host only. (See summary.t for details)


From nancy Tue Aug 18 10:18:57 1987
Received: from kessel by moth; 18 AUG 87 10:18:57 PDT
From: nancy (Nancy Mohler)
To: aric, chip, farmer
Cc: sda
Received: by kessel; 18 AUG 87 10:18:50 PDT
Subject: HabiSchedule
Status: RO

just left message w/Rob for him to confirm or advise on this proposed
schedule update, as soon as he can cover w/Janet & Cathy (Cathy's out
here this week):

8/20 start alpha III w/version 6.2
8/31 pre-beta analysis week
9/7 start beta
10/5 final code
10/12 ship to QL subscribers

He was aware of region proc crash last night, but didn't know if it was
caused by something that would delay alpha III. 

Randy, please let me know as soon as you hear anything from Janet.

thanks.



From nancy Wed Aug 19 10:01:17 1987
Received: from kessel by moth; 19 AUG 87 10:01:17 PDT
From: nancy (Nancy Mohler)
To: farmer
Cc: aric, chip, sda
Received: by kessel; 19 AUG 87 10:01:12 PDT
Subject: HabiStatus
Status: RO

per Rob, start of alpha III is on hold pending Janet diagnosing Pointers bug.
that's probably what's caused region proc crashes &/or meltdowns.  She's
putting in diagnostics to confirm that region proc crashes/meltdowns are
being caused by host, & figure out how to fix.  They don't know if there are
any problems w/the 6.2 disk, but it is not being duplicated for alpha III
until Janet has fixed the host-based pointers bug, & they're confident that
region proc crashes are stopped.

Rob promised to rattle cages & get more people on testing tonight.  He knew
of 2 meltdowns & no region proc crashes last night.

what's you're understanding of the pointers bug delaying alpha III?  thanks.



From farmer Wed Aug 19 10:23:24 1987
Received: by moth; 19 AUG 87 10:23:24 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: nancy
Cc: aric, chip, sda
Subject: Re:  HabiStatus
Status: RO

My understanding:
The problem is pretty serious, and Janet is hard at work on it.
In a nutshell, the host gets confused about what object is where in
the Stratus' memory, and feeds the Commedore bad message packets.
This accounts for the last three FE#7s, and is supposed to account
for the meltdowns (not confirmed, but likely).

Note: Rob seems to be good at getting accurate descriptions to you, I
	am glad that communications are getting clearer.

;)

From nancy Wed Aug 19 17:55:40 1987
Received: from kessel by moth; 19 AUG 87 17:55:40 PDT
From: nancy (Nancy Mohler)
To: farmer
Cc: aric, chip, sda
Received: by kessel; 19 AUG 87 17:55:34 PDT
Subject: Cathy
Status: RO

said she'd talk to Janet in the morning about getting 6.2 dup'd to send out
Friday.  from her point of view, more testers are needed to replicate 2 non-
host related meltdowns that may be caused by hardware--one suspected new
vic chip and one suspected disk drive.

certainly hope Janet is able to trap the host pointer bug tonight.



From nancy Thu Aug 20 17:09:16 1987
Received: from kessel by moth; 20 AUG 87 17:09:16 PDT
From: nancy (Nancy Mohler)
To: farmer
Cc: aric, chip, sda
Received: by kessel; 20 AUG 87 17:09:12 PDT
Subject: Alpha III
Status: RO

per Cathy, 6.2 will be sent next day delivery on Monday to alpha phase III
testers, assuming that the FE#2 you're researching doesn't require a disk
change.  you & I need to talk to Rob & Janet in the morning, as soon as you
know if the FE#2 should delay us.

Janet is sorting through the info who has on the pointer bug--it does not
delay start of alpha III.

whew!  good luck tracking down the FE#2.



From farmer Fri Aug 21 08:21:44 1987
Received: by moth; 21 AUG 87 08:21:44 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: nancy
Cc: aric, chip, sda
Subject: Re:  Alpha III
Status: RO

The fatal error will NOT delay us.
Error finding is what Alpha is for!
We ship Monday. (Period)

From farmer Fri Aug 21 15:39:39 1987
Received: by moth; 21 AUG 87 15:39:39 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer,chip,aric,nancy,sda
Subject: And they said
Status: RO


that it would never happen:
Alpha test III, Ships from Quantum Monday, overnight mail to 60 users!

(The dump they were holding WILL NOT hold us up!)

---- and there was much rejoicing ----

From farmer Mon Aug 24 07:51:49 1987
Received: by moth; 24 AUG 87 07:51:49 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: aric
Cc: chip
Subject: Need
Status: RO

Need help...
(Today, top prio.)
Do you know the region # ranges of the turfs you added to habitat?
It seems the Turf file was never updated, and there are only 6 turves left!
Lets talk
Thanks.

From nancy Tue Aug 25 14:13:00 1987
Received: from kessel by moth; 25 AUG 87 14:13:00 PDT
From: nancy (Nancy Mohler)
To: chip, farmer
Cc: sda
Received: by kessel; 25 AUG 87 14:12:56 PDT
Subject: alpha III
Status: RO

cathy said 35 went out today, & 35 going tomorrow.  2-day delivery guaranteed,
so should see many new testers on Thursday night.

re: cooties game, she thought exciting, but concerned that it'd lose appeal
fast if remains in so obvious a place or isn't limited somehow (like "Don't
press this button during a full moon").  your thoughts?

best case beta start they're thinking is 3 weeks away:  major alpha testing
week of 8/31 (next week), time for evaluation & disk rev week of 9/7, send
out beta disk week of 9/14.

Cathy will be out here week of 9/14 for AppleFest that Friday, Sat & Sun.


From nancy Wed Aug 26 20:13:19 1987
Received: from kessel by moth; 26 AUG 87 20:13:19 PDT
From: nancy (Nancy Mohler)
To: chip
Cc: aric, wendy
Received: by kessel; 26 AUG 87 20:13:16 PDT
Subject: Habitat boot screen
Status: RO

this goes back a few weeks--not sure if Aric was ever answered about
approval of copyright notice.

(c) 1987 LFL.  All rights reserved.

at the top of the screen if fine.  if there's room, write out
Lucasfilm, Ltd.

thanks.



From nancy Thu Aug 27 09:57:14 1987
Received: from kessel by moth; 27 AUG 87 09:57:14 PDT
From: nancy (Nancy Mohler)
To: farmer
Cc: aric, chip, sda
Received: by kessel; 27 AUG 87 09:57:08 PDT
Subject: Cathy
Status: RO

will talk w/you next Friday to review how the week of alpha3 testing went, &
then decide whether to buy tickets for Janet, Rob & her to come out here the
following week.

if all goes well next week, they'll plan to meet here Thursday & Friday,
9/10 & 11, to prepare for beta start the following week.

they're sounding real positive.  Cathy was thrilled to see books in the
library, & to buy a copy of the rant.

she reminded us to please keep in mind
how we take advantage of our new testers' experiences in Habitat--follow,
watch, learn how they learn, rather that lead them around.

thanks.

From chip Mon Aug 31 14:07:45 1987
Received: by moth; 31 AUG 87 14:07:45 PDT
From: chip (Chip Morningstar -- "Software Without Moving Parts")
To: aric, chip, farmer, nancy, sda
Subject: Good news/Bad news
Status: R

Just got a call from Janet.
The GOOD news is that the load problems people were experiencing were a result
of a minor system configuration difficulty which is easily corrected.
The BAD news is that since the fix involves the running system it needs to be
thoroughly tested before they put it on line, so they don't have enough time to
fix it today before production comes up (which is about an hour from now), so
Habitat is down tonight and we will resume testing tomorrow.


From farmer Mon Aug 31 09:04:55 1987
Received: by moth; 31 AUG 87 09:04:55 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer,chip,aric,nancy,sda
Subject: Habitat
Status: RO


Habitat is having some pretty heavy problems on the host side:
It is 1) using up all available buffers &
2) using more CPU than they think is correct.

The users have seen these problems as 5-10 minute region transition times
(Often reporting them as hangs).

Janet is on top of it. She will call as soon as she knows what is going on.
(Habitat was shut down for the latter half of Sunday, beacuse problem #1
above was slowing down (considerably) other parts of Qlink.)

I guess it was about time for THEM to drop a shoe, eh?
;) <- Keeping a stiff upper lip, printing out 45 pages of arfs & comments

More data as quick as I get it...

From farmer Tue Sep  1 08:53:48 1987
Received: by moth; 01 SEP 87 08:53:48 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer,chip,aric,nancy,sda
Subject: Habitat
Status: RO

Is still not quite back up yet.
I have some info that I think we should be aware of:
The hostheap has been taken care of, but quantum is concerned about
the early Habitat statistics on CPU useage.
The reason Habitat was messed up a little (when I was on) is that
Janet had to recompile everything with profiling in. This introduced some
small complications. The message I got was this:
'The CPU usage was so high, that 'extrapolated' out Habitat (in it current
state) could not be run at currnt Plus Time rates.'

This was Mark's opinion from a 2.5 days of testing Fri-Sun.
It is by no means conclusive, and The Profiler will probably tell
use of some silly overhead that can be streamlined out of the system.

Not time to panic yet, but we all have STRONG interest in the actual figures.
(actualy, to us here a LFL, this isn't really a suprise (for once :))

From farmer Mon Aug 31 10:52:34 1987
Received: by moth; 31 AUG 87 10:52:34 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: farmer,chip,aric,nancy,sda
Subject: OK
Status: RO


I printed 45 pages(!) of arfs and comments...the distillation:
(in order of number of times reported)

This is a summary only, and not comprehensive.

#1 The Host delays are really awful
#2 The system crashed (at least once)
#3 Habitat is VERY finicky about extra hardware being connected.
#4 SOME SX64 users have been unable to get in.
#5 There were some FEs (most notable, a matching set of corrupt heaps)
#6 Thieving is a point of some consternation..Perhaps we should
	a) have Steal Free Zones (to protect newcommers)
	b) prevent teft from stoned avatars.
#7 Tokens_PUT should do Tokens_DO. Tokens need a way to split
#8 And minor spelling and other small things.

The signal to noise ratio on these reports is not very high, but
the feedback is beginning to show some clear trends:
The Host is sick, and needs a continued shakedown (when Janet
has atleast the buffers under control)
The C64(?) is still getting fatal errors, but they seem to come
in clusters (several people, in the same place get an error) which
suggests a problem with data (bad object/class descriptor or something).

From farmer Tue Sep  1 08:28:49 1987
Received: from shem by moth; 01 SEP 87 08:28:49 PDT
From: farmer 
To: chip
Received: by shem; 01 SEP 87 08:28:47 PDT
Subject: Lets talk about
Status: RO


Steal free zones & removing WFZ from 'out-of-town' areas.
Can't we just change the ghu class defines file?


From farmer Tue Sep  1 08:30:24 1987
Received: by moth; 01 SEP 87 08:30:24 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: chip
Subject: keepin gyou busy..
Status: RO


I would be REAL nice if at least the 'd' function would work from
ghu's oracle function.

From farmer Tue Sep  1 09:55:50 1987
Received: by moth; 01 SEP 87 09:55:50 PDT
From: farmer (Randall Farmer) (What do you mean ARTIFICIAL intelligence?)
To: chip
Subject: Since
Status: RO


Since we are moneying with things...
I would like to add a type field to the burearcrats.
(So each crat can have customized responces)
