amulet (magic)
aquarium (fish swimming in tank)
atm (get money from bank account, deposit money in account)
avatar (our hero)
bag (useful container)
ball (for throwing)
bed (you can sit in it only, no laying (sorry))
book (holds text; newspaper is a kind of book)
boomerang (doesn't work)
bottle (fill with water, pour out again)
box (another container)
bridge (scenic object)
building (scenic object)
bush (scenic object)
chair (you can sit in it)
changomatic (changes color/pattern of stuff in your turf)
chest (chest of drawers; you can put stuff in it)
club (for beating on people with)
coke machine (steals your money)
compass (points west)
couch (you can sit on it)
countertop (for stores)
crystal ball (talks to the oracle)
display case (for stores)
door (opens and closes)
dropbox (for mailing letters)
drugs (with a variety of effects)
escape device (takes you home)
fake gun ("BANG!")
fence (scenic object)
flag (scenic object, prop)
flashlight (lights the dark places)
floor lamp (ditto)
fortune machine (tells your fortune)
fountain (lets you talk to the oracle)
frisbee (doesn't work)
garbage can (gets rid of stuff)
gemstone (valuable and magical)
grenade (blows things to bits)
ground (scenic object)
gun (shoots other people and things)
hand of god (blasts undesirables on behalf of the system operators)
head (avatar head)
hole (hole in the ground)
hot tub (hang out spot)
house cat (just sits there)
impassable (scenic object)
instant object pill (add water, it turns into something; not yet working)
jacket (clothing)
jukebox (doesn't work yet)
key (opens locked doors and containers)
knick knack (various minor objects, some magical)
knife (weapon)
magic lamp (has genie who grants a wish)
magic staff (generic magic item)
magic wand (ditto)
mailbox (lets you send and recieve mail)
matchbook (matches all used up, contains advertisement)
movie camera (not yet working)
pants (clothing)
paper (you can write notes on it and leave them for others)
picture (various pictures on the wall)
plant (scenic object)
pond (scenic object)
ring (magic ring; can't actually wear it)
rock (scenic object)
safe (lockbox)
security device (keeps other avatars out of your region)
sensor (senses things you can't see)
sex changer (self descriptive)
shirt (clothing)
shovel (digs up holes)
sign (scenic object)
sky (scenic object)
street (scenic object)
streetlamp (scenic object)
stun gun (disables other avatars without killing them)
table (you can put stuff on it)
teleport booth (gets you from place-to-place, long distance)
ticket (admission to restricted areas)
tokens (money)
trapezoid (generic scenic building block)
tree (scenic object)
vendo (sells stuff)
wall (scenic object)
wind up toy (broken)
window (scenic object)
