1 -- class field descriptor (read_class_info/class)
2 -- class field init (read_class_info/class)
3 -- define tag (build_define_tag/class)
4 -- field list (build_field_list/class)
5 -- field descriptor (build_field/class)
6 -- field descriptor (c$define/class)
7 -- init value (fill_in_init/class)
8 -- command descriptor (build_command/command)
9 -- command list descriptor (save_command/command)
10 -- value descriptor (create_value/expr)
11 -- string (create_value_from_field/expr)
12 -- bitstring (create_value_from_field/expr)
13 -- varstring (create_value_from_field/expr)
14 -- word string (create_value_from_field/expr)
15 -- array descriptor (lookup_array/expr)
16 -- value list descriptor (build_value_list/expr)
17 -- expr struct (build_expr_noid/expr)
18 -- bitstring (build_lex_result_bitstring/lex)
19 -- string (copy_string/stdio)
20 -- symbol table entry (new_symbol/symbols)
21 -- relative id list (c$cook/add)
22 -- strings from environ (unbuffer_string/environ)
23 -- bitstrings from environ (unbuffer_bitstring/environ)
24 -- command list descriptor (unsave_code/envcode)
25 -- command entry (unsave_command/envcode)
26 -- value list entry (unbuffer_value_list/envcode)
27 -- expr entry (unbuffer_value/envcode)
